definitions:
  models.Index:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/app/index:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Index'
      summary: 健康状态
swagger: "2.0"
